In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/Samdan Shaik/Desktop/seawater/input_data.csv")
df

,Temperature (deg C),Chlorinity (ppt),Salinity (%),Conductance 1/(ohm.cm)
0,0,1,0.1,0.001839
1,0,2,0.2,0.003556
2,0,3,0.3,0.005187
3,0,4,0.4,0.006758
4,0,5,0.5,0.008327
...,...,...,...,...
127,30,18,1.8,0.049677
128,30,19,1.9,0.052127
129,30,20,2.0,0.054551
130,30,21,2.1,0.056949
131,30,22,2.2,0.059321

In [7]:
df.head(10)

   Temperature (deg C)  Chlorinity (ppt)  Salinity (%)  Conductance 1/(ohm.cm)
0                    0                 1           0.1                0.001839
1                    0                 2           0.2                0.003556
2                    0                 3           0.3                0.005187
3                    0                 4           0.4                0.006758
4                    0                 5           0.5                0.008327
5                    0                 6           0.6                0.009878
6                    0                 7           0.7                0.011404
7                    0                 8           0.8                0.012905
8                    0                 9           0.9                0.014388
9                    0                10           1.0                0.015852

In [8]:
df.tail(10)

,Temperature (deg C),Chlorinity (ppt),Salinity (%),Conductance 1/(ohm.cm)
122,30,13,1.3,0.037075
123,30,14,1.4,0.039638
124,30,15,1.5,0.042180
125,30,16,1.6,0.044701
126,30,17,1.7,0.047201
127,30,18,1.8,0.049677
128,30,19,1.9,0.052127
129,30,20,2.0,0.054551
130,30,21,2.1,0.056949
131,30,22,2.2,0.059321

In [9]:
df.describe()

,Temperature (deg C),Chlorinity (ppt),Salinity (%),Conductance 1/(ohm.cm)
count,132.000000,132.000000,132.000000,132.000000
mean,13.333333,11.500000,1.150000,0.024976
std,9.897696,6.368458,0.636846,0.014156
min,0.000000,1.000000,0.100000,0.001839
25%,5.000000,6.000000,0.600000,0.013168
50%,12.500000,11.500000,1.150000,0.024175
75%,20.000000,17.000000,1.700000,0.034778
max,30.000000,22.000000,2.200000,0.059321

In [19]:
def calculate_resistivity(temperature, salinity):
    # Filtering the DataFrame based on the provided temperature and salinity
    value = df[(df['Temperature (deg C)'] == temperature) & (df['Salinity (%)'] == salinity)]
    
    if value.empty:
        filtered_data = df
        conductance = value['Conductance 1/(ohm.cm)'].mean()
    else:
        conductance = value['Conductance 1/(ohm.cm)'].values[0] 
    
    resistivity = 1 / conductance
    
    return resistivity

temperature = 20
salinity = 0.8 

result = calculate_resistivity(temperature, salinity)
print("Resistivity:", round(result, 3))

Resistivity: 46.481

In [15]:
print(df.columns)

Index(['Temperature (deg C)', 'Chlorinity (ppt)', 'Salinity (%)',
       'Conductance 1/(ohm.cm)'],
      dtype='object')